### ISSUE TITLE
debian pkg procedure is broken

### ISSUE THREAD

**Issue by Ole2mail** [vpp-dev/vpp#13]
for a reason, there are no tags registered and version information isn't available,
make pkg-deb
is broken with an error:

`dpkg-deb: error: parsing file 'debian/vpp/DEBIAN/control' near line 14 package 'vpp':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-dbg/DEBIAN/control' near line 11 package 'vpp-dbg':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-dbg .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-dev/DEBIAN/control' near line 12 package 'vpp-dev':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-dev .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-lib/DEBIAN/control' near line 18 package 'vpp-lib':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-lib .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-plugins/DEBIAN/control' near line 12 package 'vpp-plugins':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-plugins .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-api-lua/DEBIAN/control' near line 13 package 'vpp-api-lua':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-api-lua .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-api-java/DEBIAN/control' near line 13 package 'vpp-api-java':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-api-java .. returned exit code 2
dpkg-deb: error: parsing file 'debian/vpp-api-python/DEBIAN/control' near line 13 package 'vpp-api-python':
 empty value for version
dh_builddeb: dpkg-deb --build debian/vpp-api-python .. returned exit code 2
debian/rules:21: recipe for target 'binary' failed
make[2]: *** [binary] Error 1
make[2]: Leaving directory '/home/user/Projects/vpp.master/build-root/deb'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
/home/user/Projects/vpp.master/build-data/platforms.mk:20: recipe for target 'install-deb' failed
make[1]: *** [install-deb] Error 1
make[1]: Leaving directory '/home/user/Projects/vpp.master/build-root'
Makefile:324: recipe for target 'pkg-deb' failed
make: *** [pkg-deb] Error 2
`

having top line of the changelog following:
`vpp (-release) unstable; urgency=low
`

however,
git review master branch version succeeded to obtain new version tag (
vpp (17.07-rc0~200-g1ea82df) unstable; urgency=low
) and builds deb packages well.

**Comment by dmarion** [comment]
Please use main repo available at git.fd.io and report issues at vpp-dev@fd.io. We don't keep github repo in sync, it is only used occasionally for development purposes....
